version: '3.8'

services:
  lavalink:
    image: 'ghcr.io/lavalink-devs/lavalink:4'
    container_name: lavalink
    restart: unless-stopped
    volumes:
      # هذا السطر تم تعديله ليقرأ من المجلد الصحيح الذي ظهر في صورتك
      - './lavalink-config/application.yml:/opt/Lavalink/application.yml'
    networks:
      - music-network

  music-bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: music-bot
    restart: unless-stopped
    environment:
      - 'DISCORD_TOKEN=${DISCORD_TOKEN}'
      - 'CLIENT_ID=${CLIENT_ID}'
      - 'LAVALINK_PASSWORD=${LAVALINK_PASSWORD}'
      - 'LAVALINK_HOST=lavalink'
      - 'LAVALINK_PORT=2333'
    depends_on:
      - lavalink
    networks:
      - music-network

networks:
  music-network:
    driver: bridge
    attachable: true
