server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "Nmk057007"
    sources:
      youtube: false
      soundcloud: true
      http: true

plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.4"
    snapshot: false

pluginsConfig:
  youtube:
    enabled: true

logging:
  level:
    lavalink: INFO
