server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.12.0"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: "Nmk057007"
    sources:
      youtube: false
      soundcloud: true
      http: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - ANDROID
      - TVHTML5EMBEDDED

logging:
  level:
    root: INFO
    lavalink: INFO
